In [2]:
import pandas as pd

In [3]:
df= pd.read_csv("test_data.csv")

In [4]:
df

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,791,792,0.0,1,0.2000,0.050749,0.0,1,NaN,0.0,1,0,0,0,0,0,1
1,792,793,0.0,0,0.3500,0.135753,NaN,0,1.0,1.0,0,0,0,1,0,0,1
2,793,794,NaN,1,0.3500,0.059914,1.0,0,0.0,0.0,1,0,0,0,1,0,0
3,794,795,0.0,1,0.3125,0.015412,0.0,0,1.0,0.0,1,0,0,0,0,0,1
4,795,796,0.0,1,0.4875,0.025374,0.0,1,0.0,0.0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,886,887,0.0,1,0.3375,0.025374,0.0,1,0.0,0.0,1,0,0,0,0,0,1
96,887,888,1.0,0,0.2375,0.058556,1.0,0,0.0,0.0,0,0,0,1,0,0,1
97,888,889,0.0,0,0.3500,0.045771,0.0,0,1.0,0.3,0,0,0,1,0,0,1
98,889,890,1.0,1,0.3250,0.058556,1.0,0,0.0,0.0,1,0,0,0,1,0,0
99,890,891,0.0,1,0.4000,0.015127,0.0,0,1.0,0.0,1,0,0,0,0,1,0

In [8]:
import os   #to display which files stores in folder
os.listdir()

['.ipynb_checkpoints',
 'pandas.ipynb',
 'pandas_lib.ipynb',
 'Student_Marks.csv',
 'test_data.csv']

In [5]:
df.head() # for display top 5

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,791,792,0.0,1,0.2000,0.050749,0.0,1,NaN,0.0,1,0,0,0,0,0,1
1,792,793,0.0,0,0.3500,0.135753,NaN,0,1.0,1.0,0,0,0,1,0,0,1
2,793,794,NaN,1,0.3500,0.059914,1.0,0,0.0,0.0,1,0,0,0,1,0,0
3,794,795,0.0,1,0.3125,0.015412,0.0,0,1.0,0.0,1,0,0,0,0,0,1
4,795,796,0.0,1,0.4875,0.025374,0.0,1,0.0,0.0,1,0,0,0,0,0,1

In [6]:
df.tail() # for last 5

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
95,886,887,0.0,1,0.3375,0.025374,0.0,1,0.0,0.0,1,0,0,0,0,0,1
96,887,888,1.0,0,0.2375,0.058556,1.0,0,0.0,0.0,0,0,0,1,0,0,1
97,888,889,0.0,0,0.3500,0.045771,0.0,0,1.0,0.3,0,0,0,1,0,0,1
98,889,890,1.0,1,0.3250,0.058556,1.0,0,0.0,0.0,1,0,0,0,1,0,0
99,890,891,0.0,1,0.4000,0.015127,0.0,0,1.0,0.0,1,0,0,0,0,1,0

In [7]:
df.describe()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
count,100.000000,100.000000,99.000000,100.000000,100.000000,100.000000,99.000000,100.000000,99.000000,100.000000,100.000000,100.00,100.00000,100.000000,100.00000,100.000000,100.000000
mean,840.500000,841.500000,0.363636,0.650000,0.355656,0.048333,0.232323,0.200000,0.575758,0.104000,0.770000,0.01,0.08000,0.140000,0.21000,0.040000,0.740000
std,29.011492,29.011492,0.483494,0.479372,0.161188,0.053429,0.424463,0.402015,0.496743,0.207885,0.422953,0.10,0.27266,0.348735,0.40936,0.196946,0.440844
min,791.000000,792.000000,0.000000,0.000000,0.005250,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00,0.00000,0.000000,0.00000,0.000000,0.000000
25%,815.750000,816.750000,0.000000,0.000000,0.271875,0.015412,0.000000,0.000000,0.000000,0.000000,1.000000,0.00,0.00000,0.000000,0.00000,0.000000,0.000000
50%,840.500000,841.500000,0.000000,1.000000,0.350000,0.025374,0.000000,0.000000,1.000000,0.000000,1.000000,0.00,0.00000,0.000000,0.00000,0.000000,1.000000
75%,865.250000,866.250000,1.000000,1.000000,0.426563,0.058556,0.000000,0.000000,1.000000,0.100000,1.000000,0.00,0.00000,0.000000,0.00000,0.000000,1.000000
max,890.000000,891.000000,1.000000,1.000000,0.925000,0.321798,1.000000,1.000000,1.000000,1.000000,1.000000,1.00,1.00000,1.000000,1.00000,1.000000,1.000000

In [5]:
df.columns

Index(['Unnamed: 0', 'PassengerId', 'Survived', 'Sex', 'Age', 'Fare',
       'Pclass_1', 'Pclass_2', 'Pclass_3', 'Family_size', 'Title_1', 'Title_2',
       'Title_3', 'Title_4', 'Emb_1', 'Emb_2', 'Emb_3'],
      dtype='object')

In [14]:
a= df["Sex"][0:10]

In [15]:
a

0    1
1    0
2    1
3    1
4    1
5    0
6    0
7    1
8    0
9    1
Name: Sex, dtype: int64

In [16]:
type(a)

pandas.core.series.Series

In [17]:
l= ["nandini","a2","a3","a4","a5","a6","a7","a8","a9","a10"]

In [18]:
pd.Series(a,index=l)

nandini   NaN
a2        NaN
a3        NaN
a4        NaN
a5        NaN
a6        NaN
a7        NaN
a8        NaN
a9        NaN
a10       NaN
Name: Sex, dtype: float64

In [19]:
pd.Series(list(a),index=l)

nandini    1
a2         0
a3         1
a4         1
a5         1
a6         0
a7         0
a8         1
a9         0
a10        1
dtype: int64

In [21]:
m1=pd.Series([100,200,300,400,500],index=[1,2,3,4,5])

In [22]:
m1

1    100
2    200
3    300
4    400
5    500
dtype: int64

In [24]:
m2 = pd.Series([600,700,800,900], index=[6,7,8,9])
m2

6    600
7    700
8    800
9    900
dtype: int64

In [30]:
m3= pd.concat([m1,m2])
m3

1    100
2    200
3    300
4    400
5    500
6    600
7    700
8    800
9    900
dtype: int64

In [33]:
m3[9]

np.int64(900)

In [28]:
#for dlt column
df.drop("Survived", axis=1)  #not dlt permantly axis=1 for column, axis=0 row

,Unnamed: 0,PassengerId,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,791,792,1,0.2000,0.050749,0,1,0,0.0,1,0,0,0,0,0,1
1,792,793,0,0.3500,0.135753,0,0,1,1.0,0,0,0,1,0,0,1
2,793,794,1,0.3500,0.059914,1,0,0,0.0,1,0,0,0,1,0,0
4,795,796,1,0.4875,0.025374,0,1,0,0.0,1,0,0,0,0,0,1
5,796,797,0,0.6125,0.050610,1,0,0,0.0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,886,887,1,0.3375,0.025374,0,1,0,0.0,1,0,0,0,0,0,1
96,887,888,0,0.2375,0.058556,1,0,0,0.0,0,0,0,1,0,0,1
97,888,889,0,0.3500,0.045771,0,0,1,0.3,0,0,0,1,0,0,1
98,889,890,1,0.3250,0.058556,1,0,0,0.0,1,0,0,0,1,0,0
99,890,891,1,0.4000,0.015127,0,0,1,0.0,1,0,0,0,0,1,0

In [49]:
df.drop("Survived", axis=1 , inplace= True)  # dlt permantly using inplace = True

In [29]:
df.head()

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,791,792,0,1,0.2000,0.050749,0,1,0,0.0,1,0,0,0,0,0,1
1,792,793,0,0,0.3500,0.135753,0,0,1,1.0,0,0,0,1,0,0,1
2,793,794,0,1,0.3500,0.059914,1,0,0,0.0,1,0,0,0,1,0,0
4,795,796,0,1,0.4875,0.025374,0,1,0,0.0,1,0,0,0,0,0,1
5,796,797,1,0,0.6125,0.050610,1,0,0,0.0,0,1,0,0,0,0,1

In [32]:
#for dlt rows
df.drop(4) # not dlt permantly , use inplace= True for permantly dlt

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,791,792,0,1,0.2000,0.050749,0,1,0,0.0,1,0,0,0,0,0,1
1,792,793,0,0,0.3500,0.135753,0,0,1,1.0,0,0,0,1,0,0,1
2,793,794,0,1,0.3500,0.059914,1,0,0,0.0,1,0,0,0,1,0,0
5,796,797,1,0,0.6125,0.050610,1,0,0,0.0,0,1,0,0,0,0,1
6,797,798,1,0,0.3875,0.016949,0,0,1,0.0,1,0,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,886,887,0,1,0.3375,0.025374,0,1,0,0.0,1,0,0,0,0,0,1
96,887,888,1,0,0.2375,0.058556,1,0,0,0.0,0,0,0,1,0,0,1
97,888,889,0,0,0.3500,0.045771,0,0,1,0.3,0,0,0,1,0,0,1
98,889,890,1,1,0.3250,0.058556,1,0,0,0.0,1,0,0,0,1,0,0
99,890,891,0,1,0.4000,0.015127,0,0,1,0.0,1,0,0,0,0,1,0

In [14]:
# make dataframe from dictonary 
d= {"key1": [1,2,3,4,5],
    "key2": [6,7,8,9,10],
    "key3" :[11,12,13,14,15]
   }

In [15]:
print(d)

{'key1': [1, 2, 3, 4, 5], 'key2': [6, 7, 8, 9, 10], 'key3': [11, 12, 13, 14, 15]}

In [18]:
pd.DataFrame(d)

   key1  key2  key3
0     1     6    11
1     2     7    12
2     3     8    13
3     4     9    14
4     5    10    15

In [37]:
# clean data
#1. remove missing values rows (NaN)
df.dropna(inplace =True) # dlt permantly

In [38]:
df

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,791,792,0,1,0.2000,0.050749,0,1,0,0.0,1,0,0,0,0,0,1
1,792,793,0,0,0.3500,0.135753,0,0,1,1.0,0,0,0,1,0,0,1
2,793,794,0,1,0.3500,0.059914,1,0,0,0.0,1,0,0,0,1,0,0
4,795,796,0,1,0.4875,0.025374,0,1,0,0.0,1,0,0,0,0,0,1
5,796,797,1,0,0.6125,0.050610,1,0,0,0.0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,886,887,0,1,0.3375,0.025374,0,1,0,0.0,1,0,0,0,0,0,1
96,887,888,1,0,0.2375,0.058556,1,0,0,0.0,0,0,0,1,0,0,1
97,888,889,0,0,0.3500,0.045771,0,0,1,0.3,0,0,0,1,0,0,1
98,889,890,1,1,0.3250,0.058556,1,0,0,0.0,1,0,0,0,1,0,0
99,890,891,0,1,0.4000,0.015127,0,0,1,0.0,1,0,0,0,0,1,0

In [24]:
#2. remove missing values (Nan) columns
df.dropna(axis= 1, inplace= True)

In [27]:
df

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,791,792,0,1,0.2000,0.050749,0,1,0,0.0,1,0,0,0,0,0,1
1,792,793,0,0,0.3500,0.135753,0,0,1,1.0,0,0,0,1,0,0,1
2,793,794,0,1,0.3500,0.059914,1,0,0,0.0,1,0,0,0,1,0,0
4,795,796,0,1,0.4875,0.025374,0,1,0,0.0,1,0,0,0,0,0,1
5,796,797,1,0,0.6125,0.050610,1,0,0,0.0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,886,887,0,1,0.3375,0.025374,0,1,0,0.0,1,0,0,0,0,0,1
96,887,888,1,0,0.2375,0.058556,1,0,0,0.0,0,0,0,1,0,0,1
97,888,889,0,0,0.3500,0.045771,0,0,1,0.3,0,0,0,1,0,0,1
98,889,890,1,1,0.3250,0.058556,1,0,0,0.0,1,0,0,0,1,0,0
99,890,891,0,1,0.4000,0.015127,0,0,1,0.0,1,0,0,0,0,1,0

In [39]:
# 3. fill value "Nandini" at "NaN" misssing value 
df.fillna("Nandini")
df

,Unnamed: 0,PassengerId,Survived,Sex,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Family_size,Title_1,Title_2,Title_3,Title_4,Emb_1,Emb_2,Emb_3
0,791,792,0,1,0.2000,0.050749,0,1,0,0.0,1,0,0,0,0,0,1
1,792,793,0,0,0.3500,0.135753,0,0,1,1.0,0,0,0,1,0,0,1
2,793,794,0,1,0.3500,0.059914,1,0,0,0.0,1,0,0,0,1,0,0
4,795,796,0,1,0.4875,0.025374,0,1,0,0.0,1,0,0,0,0,0,1
5,796,797,1,0,0.6125,0.050610,1,0,0,0.0,0,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,886,887,0,1,0.3375,0.025374,0,1,0,0.0,1,0,0,0,0,0,1
96,887,888,1,0,0.2375,0.058556,1,0,0,0.0,0,0,0,1,0,0,1
97,888,889,0,0,0.3500,0.045771,0,0,1,0.3,0,0,0,1,0,0,1
98,889,890,1,1,0.3250,0.058556,1,0,0,0.0,1,0,0,0,1,0,0
99,890,891,0,1,0.4000,0.015127,0,0,1,0.0,1,0,0,0,0,1,0